import styled from "styled-components";

export const Whatever3 = styled.p`
  opacity: 1;
  border: 1px solid;
  text-display: center;
  background-color: #11111b;
  border-radius: 200px;
  text-align: center;
  height: 40px;
  width: 150px;
  font-size: large;
  padding: 10px;
  margin-left: 30px;
  margin-top: 10px;
  font-size: 0.9em;
  font-family: sans-serif;
  min-width: 200px;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.6);
`;
export const Whatever1 = styled.div`
  color: var(--white);
  opacity: 1;
  display: inline-block;
  text-display: center;
  background-color: #6e6c7b;
  border-radius: 200px;
  text-align: center;
  height: 40px;
  width: 150px;
  padding: 10px;
  margin-left: 50px;
  margin-top: 20px;
  font-size: 0.9em;
  font-family: sans-serif;
  min-width: 100px;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.8);
`;
export const Whatever2 = styled.div`
  border-collapse: collapse;
  margin: 25px 0;
  font-size: 0.9em;
  font-family: sans-serif;
  min-width: 400px;
  box-shadow: 0 0 20px rgba(120, 120, 120, 0.4);
  background-color: #444444;
  border-radius: 50px;
  height: 440px;
  width: 1250px;
  text-align: center;
`;
