name: Node.js CI for Main Branch

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - name: Push build for EC2
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'build'
        destination-github-username: 'Wanchester'
        destination-repository-name: 'sd-front-ec2'
        user-email: 'quyenjd@users.noreply.github.com'
        user-name: 'auto-ec2-builder'
        commit-message: 'Last build at ORIGIN_COMMIT'
